[package]
name = "network-math"
version = "0.1.0"
authors = ["Cassie Jones <code@witchoflight.com>"]
edition = "2018"

[dependencies]
reqwest = "0.7"
iron = "0.5"

once_cell = "1.4.1"

log = "0.3"
env_logger = "0.4"
